apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: flask-app
        image: flashball13/service_project:1.3  # Replace this with the image of your web application
        ports:
        - containerPort: 5000

